"""Vanilla Minecraft display names.

Modern names are based on Minecraft 26.2's English localization.
Legacy achievement names are based on Minecraft 1.8.9's English localization.
"""

VANILLA_ADVANCEMENT_TITLES = {
    "minecraft:adventure/adventuring_time": "Adventuring Time",
    "minecraft:adventure/arbalistic": "Arbalistic",
    "minecraft:adventure/avoid_vibration": "Sneak 100",
    "minecraft:adventure/blowback": "Blowback",
    "minecraft:adventure/brush_armadillo": "Isn't It Scute?",
    "minecraft:adventure/bullseye": "Bullseye",
    "minecraft:adventure/craft_decorated_pot_using_only_sherds": "Careful Restoration",
    "minecraft:adventure/crafters_crafting_crafters": "Crafters Crafting Crafters",
    "minecraft:adventure/fall_from_world_height": "Caves & Cliffs",
    "minecraft:adventure/heart_transplanter": "Heart Transplanter",
    "minecraft:adventure/hero_of_the_village": "Hero of the Village",
    "minecraft:adventure/honey_block_slide": "Sticky Situation",
    "minecraft:adventure/kill_a_mob": "Monster Hunter",
    "minecraft:adventure/kill_all_mobs": "Monsters Hunted",
    "minecraft:adventure/kill_mob_near_sculk_catalyst": "It Spreads",
    "minecraft:adventure/lighten_up": "Lighten Up",
    "minecraft:adventure/lightning_rod_with_villager_no_fire": "Surge Protector",
    "minecraft:adventure/minecraft_trials_edition": "Minecraft: Trial(s) Edition",
    "minecraft:adventure/ol_betsy": "Ol' Betsy",
    "minecraft:adventure/overoverkill": "Over-Overkill",
    "minecraft:adventure/play_jukebox_in_meadows": "Sound of Music",
    "minecraft:adventure/read_power_from_chiseled_bookshelf": "The Power of Books",
    "minecraft:adventure/revaulting": "Revaulting",
    "minecraft:adventure/root": "Adventure",
    "minecraft:adventure/salvage_sherd": "Respecting the Remnants",
    "minecraft:adventure/shoot_arrow": "Take Aim",
    "minecraft:adventure/sleep_in_bed": "Sweet Dreams",
    "minecraft:adventure/sniper_duel": "Sniper Duel",
    "minecraft:adventure/spear_many_mobs": "Mob Kabob",
    "minecraft:adventure/spyglass_at_dragon": "Is It a Plane?",
    "minecraft:adventure/spyglass_at_ghast": "Is It a Balloon?",
    "minecraft:adventure/spyglass_at_parrot": "Is It a Bird?",
    "minecraft:adventure/summon_iron_golem": "Hired Help",
    "minecraft:adventure/throw_trident": "A Throwaway Joke",
    "minecraft:adventure/totem_of_undying": "Postmortal",
    "minecraft:adventure/trade_at_world_height": "Star Trader",
    "minecraft:adventure/trade": "What a Deal!",
    "minecraft:adventure/trim_with_all_exclusive_armor_patterns": "Smithing with Style",
    "minecraft:adventure/trim_with_any_armor_pattern": "Crafting a New Look",
    "minecraft:adventure/two_birds_one_arrow": "Two Birds, One Arrow",
    "minecraft:adventure/under_lock_and_key": "Under Lock and Key",
    "minecraft:adventure/use_lodestone": "Country Lode, Take Me Home",
    "minecraft:adventure/very_very_frightening": "Very Very Frightening",
    "minecraft:adventure/voluntary_exile": "Voluntary Exile",
    "minecraft:adventure/walk_on_powder_snow_with_leather_boots": "Light as a Rabbit",
    "minecraft:adventure/who_needs_rockets": "Who Needs Rockets?",
    "minecraft:adventure/whos_the_pillager_now": "Who's the Pillager Now?",
    "minecraft:end/dragon_breath": "You Need a Mint",
    "minecraft:end/dragon_egg": "The Next Generation",
    "minecraft:end/elytra": "Sky's the Limit",
    "minecraft:end/enter_end_gateway": "Remote Getaway",
    "minecraft:end/find_end_city": "The City at the End of the Game",
    "minecraft:end/kill_dragon": "Free the End",
    "minecraft:end/levitate": "Great View From Up Here",
    "minecraft:end/respawn_dragon": "The End... Again...",
    "minecraft:end/root": "The End",
    "minecraft:husbandry/allay_deliver_cake_to_note_block": "Birthday Song",
    "minecraft:husbandry/allay_deliver_item_to_player": "You've Got a Friend in Me",
    "minecraft:husbandry/axolotl_in_a_bucket": "The Cutest Predator",
    "minecraft:husbandry/balanced_diet": "A Balanced Diet",
    "minecraft:husbandry/breed_all_animals": "Two by Two",
    "minecraft:husbandry/breed_an_animal": "The Parrots and the Bats",
    "minecraft:husbandry/complete_catalogue": "A Complete Catalogue",
    "minecraft:husbandry/feed_snifflet": "Little Sniffs",
    "minecraft:husbandry/fishy_business": "Fishy Business",
    "minecraft:husbandry/froglights": "With Our Powers Combined!",
    "minecraft:husbandry/kill_axolotl_target": "The Healing Power of Friendship!",
    "minecraft:husbandry/leash_all_frog_variants": "When the Squad Hops into Town",
    "minecraft:husbandry/make_a_sign_glow": "Glow and Behold!",
    "minecraft:husbandry/netherite_hoe": "Serious Dedication",
    "minecraft:husbandry/obtain_sniffer_egg": "Smells Interesting",
    "minecraft:husbandry/place_dried_ghast_in_water": "Stay Hydrated!",
    "minecraft:husbandry/plant_any_sniffer_seed": "Planting the Past",
    "minecraft:husbandry/plant_seed": "A Seedy Place",
    "minecraft:husbandry/remove_wolf_armor": "Shear Brilliance",
    "minecraft:husbandry/repair_wolf_armor": "Good as New",
    "minecraft:husbandry/ride_a_boat_with_a_goat": "Whatever Floats Your Goat!",
    "minecraft:husbandry/root": "Husbandry",
    "minecraft:husbandry/safely_harvest_honey": "Bee Our Guest",
    "minecraft:husbandry/silk_touch_nest": "Total Beelocation",
    "minecraft:husbandry/tactical_fishing": "Tactical Fishing",
    "minecraft:husbandry/tadpole_in_a_bucket": "Bukkit Bukkit",
    "minecraft:husbandry/tame_an_animal": "Best Friends Forever",
    "minecraft:husbandry/uh_oh": "Uh Oh",
    "minecraft:husbandry/wax_off": "Wax Off",
    "minecraft:husbandry/wax_on": "Wax On",
    "minecraft:husbandry/whole_pack": "The Whole Pack",
    "minecraft:nether/all_effects": "How Did We Get Here?",
    "minecraft:nether/all_potions": "A Furious Cocktail",
    "minecraft:nether/brew_potion": "Local Brewery",
    "minecraft:nether/charge_respawn_anchor": "Not Quite \"Nine\" Lives",
    "minecraft:nether/create_beacon": "Bring Home the Beacon",
    "minecraft:nether/create_full_beacon": "Beaconator",
    "minecraft:nether/distract_piglin": "Oh Shiny",
    "minecraft:nether/explore_nether": "Hot Tourist Destinations",
    "minecraft:nether/fast_travel": "Subspace Bubble",
    "minecraft:nether/find_bastion": "Those Were the Days",
    "minecraft:nether/find_fortress": "A Terrible Fortress",
    "minecraft:nether/get_wither_skull": "Spooky Scary Skeleton",
    "minecraft:nether/loot_bastion": "War Pigs",
    "minecraft:nether/netherite_armor": "Cover Me in Debris",
    "minecraft:nether/obtain_ancient_debris": "Hidden in the Depths",
    "minecraft:nether/obtain_blaze_rod": "Into Fire",
    "minecraft:nether/obtain_crying_obsidian": "Who is Cutting Onions?",
    "minecraft:nether/return_to_sender": "Return to Sender",
    "minecraft:nether/ride_strider_in_overworld_lava": "Feels Like Home",
    "minecraft:nether/ride_strider": "This Boat Has Legs",
    "minecraft:nether/root": "Nether",
    "minecraft:nether/summon_wither": "Withering Heights",
    "minecraft:nether/uneasy_alliance": "Uneasy Alliance",
    "minecraft:nether/use_lodestone": "Country Lode, Take Me Home",
    "minecraft:story/cure_zombie_villager": "Zombie Doctor",
    "minecraft:story/deflect_arrow": "Not Today, Thank You",
    "minecraft:story/enchant_item": "Enchanter",
    "minecraft:story/enter_the_end": "The End?",
    "minecraft:story/enter_the_nether": "We Need to Go Deeper",
    "minecraft:story/follow_ender_eye": "Eye Spy",
    "minecraft:story/form_obsidian": "Ice Bucket Challenge",
    "minecraft:story/iron_tools": "Isn't It Iron Pick",
    "minecraft:story/lava_bucket": "Hot Stuff",
    "minecraft:story/mine_diamond": "Diamonds!",
    "minecraft:story/mine_stone": "Stone Age",
    "minecraft:story/obtain_armor": "Suit Up",
    "minecraft:story/root": "Minecraft",
    "minecraft:story/shiny_gear": "Cover Me with Diamonds",
    "minecraft:story/smelt_iron": "Acquire Hardware",
    "minecraft:story/upgrade_tools": "Getting an Upgrade"
}

LEGACY_ACHIEVEMENT_TITLES = {
    "achievement.get": "Achievement get!",
    "achievement.taken": "Taken!",
    "achievement.unknown": "???",
    "achievement.requires": "Requires '%1$s'",
    "achievement.openInventory": "Taking Inventory",
    "achievement.mineWood": "Getting Wood",
    "achievement.buildWorkBench": "Benchmarking",
    "achievement.buildPickaxe": "Time to Mine!",
    "achievement.buildFurnace": "Hot Topic",
    "achievement.acquireIron": "Acquire Hardware",
    "achievement.buildHoe": "Time to Farm!",
    "achievement.makeBread": "Bake Bread",
    "achievement.bakeCake": "The Lie",
    "achievement.buildBetterPickaxe": "Getting an Upgrade",
    "achievement.overpowered": "Overpowered",
    "achievement.cookFish": "Delicious Fish",
    "achievement.onARail": "On A Rail",
    "achievement.buildSword": "Time to Strike!",
    "achievement.killEnemy": "Monster Hunter",
    "achievement.killCow": "Cow Tipper",
    "achievement.breedCow": "Repopulation",
    "achievement.flyPig": "When Pigs Fly",
    "achievement.snipeSkeleton": "Sniper Duel",
    "achievement.diamonds": "DIAMONDS!",
    "achievement.diamondsToYou": "Diamonds to you!",
    "achievement.portal": "We Need to Go Deeper",
    "achievement.ghast": "Return to Sender",
    "achievement.blazeRod": "Into Fire",
    "achievement.potion": "Local Brewery",
    "achievement.theEnd": "The End?",
    "achievement.theEnd2": "The End.",
    "achievement.spawnWither": "The Beginning?",
    "achievement.killWither": "The Beginning.",
    "achievement.fullBeacon": "Beaconator",
    "achievement.exploreAllBiomes": "Adventuring Time",
    "achievement.enchantments": "Enchanter",
    "achievement.overkill": "Overkill",
    "achievement.bookcase": "Librarian"
}
